src/reader.rs, src/writer.rs
This makes it possible to exchange binary serialized structures between
different architectures, and reduces bandwidth.  I doubt it's even
possible to have more than 4 billions variants anyway :).
=> Use u32 to represent variant tags.

src/lib.rs, src/reader.rs, src/test.rs
When decoding, decoding errors are now isolated from `IoError`s.
Decoding is also more strict in various circumstances, see new test.
=> More robust and precise error handling.

src/lib.rs, src/reader.rs
While BufRead is preferable to avoid dog-slow performance, requiring
when no methods are called is also problematic, especially for wrappers
around Read that shouldn't necessarily need to know they're wrapping
BufRead.
=> Don't require BufRead, only Read

Cargo.toml
byteorder 0.2.9 no longer builds on rustc nightly; bumping this dependency to 0.3.1 fixes this issue
=> bump byteorder dependency to 0.3.1

src/writer.rs
So that upstream errors can derive these.
=> Derive Clone,PartialEq for EncodingError

readme.md, src/lib.rs, src/reader.rs
Fixes new rustc 2015-03-30 issue:
````
src/reader.rs:126:22: 126:42 error: the type of this value must be known in this context
src/reader.rs:126         self.read += cast(count).unwrap();
````
=> Fix for upstream rustc changes

src/refbox.rs, src/test.rs
Allows `#[derive(Debug)]` to work with things containing RefBox.
Not sure adding impls like this is sustainable.
I used to be able to do
```
impl<'a> fmt::Debug for bincode::RefBox<'a, MyLocalType> {
fn fmt(&self, fmt: &mut fmt::Formatter) -> Result<(), fmt::Error> {
write!(fmt, "RefBox({:?})", *self)
}
}
```
Locally, but recent rust has forbidden this.
=> refbox: add Debug impl

src/lib.rs
The correct syntax for module level documentation is `//!`, not `///!`. This will make the doc text appear on the crate documentation's first page.
I also moved the comment block to the top of the file so that rustdoc won't throw "expected outer comment" error.
=> Fix rustdoc comment syntax

src/refbox.rs, src/test.rs
Allows more convenient use of SliceBox where one doesn't care whether
it represents a Vec<T> or &[T] and can handle using a &[T].
=> SliceBox: allow Deref into &[T]

src/reader.rs, src/test.rs
Fixes #41 
Not sure if this style OOM issue affects other parts of the decoder.
=> check the size of seqs before trying to decode them

Cargo.toml, src/lib.rs, src/reader_serde.rs, src/refbox.rs, src/writer_serde.rs, tests/test.rs, tests/test_serde.rs
This is an initial PR that adds support for the yet-to-be-released serde version 0.5.0, so please don't merge this in until that lands. I wanted to submit it to get your input on the design and if you see if there are any gaps in the implementation.
=> Add support for serde

Cargo.toml, src/serde/reader.rs, src/serde/writer.rs, tests/test.rs
=> Support serde 0.7

src/rustc_serialize/reader.rs
It's possible to cause the bincode rustc_serialise decoder to panic with OOM even if a size limit is set. This PR makes the `read_seq` and `read_map` decoder methods check that the number of elements about to be read is not greater than the number of bytes remaining before we hit the limit. This is not a perfect solution as it sort-of assumes that all types have size 1. For instance, if the size limit is 1KB it should still be allowable to decode a `Vec` of a million `()`s whereas it shouldn't be allowable to decode a `Vec` of 500 `u32`s. With this fix, neither of these situations are handled correctly. However I don't see a solution to this, and having this fix is better than not having it.
This PR also uses `checked_add` in `read_bytes` to so that people can't use malicious data to …
=> Respect size limits in read_seq and read_map.

src/rustc_serialize/reader.rs
This reverts commit 45fcb1cebc4247a47d6d88f9e6057315237e4c03.
=> Revert "Respect size limits in read_seq and read_map."

.travis.yml, Cargo.toml, src/lib.rs, src/refbox.rs
So you are allowed to depend only on what you use.
Tests depend heavily on both of these crates, so they only run with default features on.
So did example binary, I did not modify it for simplicity and clarity.
=> Add cargo features for rustc-serialize and serde

Cargo.toml
This is a follow-up to the previous PR. I have overlooked that the `num` crate pulls `rustc-serialize` unconditionally (and it isn't used by the way), so I disabled it.
=> Don't pull `rustc-serialize` from `num`

src/serde/reader.rs, tests/test.rs
Fixes #74. 
[This](https://github.com/serde-rs/serde/pull/392) PR in `serde` fixes this problem but I don't know when and how they will release patch.
=> Fixed size array deserialization

src/rustc_serialize/mod.rs, src/rustc_serialize/reader.rs, src/serde/mod.rs, src/serde/reader.rs, tests/test.rs
* Removed some 'unused import' warnings
* Made both fields of InvalidEncoding public so it can be used without Display or Debug traits (e.g. pattern matching)
=> pub used InvalidEncoding in serde+rustc_serialize so it shows in `cargo doc`

Cargo.toml, src/serde/reader.rs, src/serde/writer.rs
=> Update to serde 0.8.0

src/rustc_serialize/writer.rs, tests/test.rs
[`read_enum_struct_variant`](https://github.com/TyOverby/bincode/blob/f06a4cfcb5b194e54d4997c200c75b88b6c3fba4/src/rustc_serialize/reader.rs#L279-L283) delegates calls to [`read_enum_variant`](https://github.com/TyOverby/bincode/blob/f06a4cfcb5b194e54d4997c200c75b88b6c3fba4/src/rustc_serialize/reader.rs#L260-L263) which expects `u32` prefix to encode a variant number. Previous implementation of [`emit_enum_struct_variant`](https://github.com/TyOverby/bincode/blob/f06a4cfcb5b194e54d4997c200c75b88b6c3fba4/src/rustc_serialize/writer.rs#L178-L187) doesn't emit it, making serialized data invalid.
=> Delegate emit_enum_struct_variant calls to emit_enum_variant

Cargo.toml, src/serde/writer.rs, tests/test.rs
Reported in IRC: user blank_name2 tried serializing `HashMap<String, HashSet<Bytes>>` vs `HashMap<String, HashSet<&Path>>`, the `&Path` version was done in ~.6 seconds while the `&[u8]` one took a full 3 seconds more.
This PR resolves the difference between the two while keeping the same serialized form.
=> More efficient serialize_bytes

Cargo.toml, src/refbox.rs, src/serde/reader.rs, src/serde/writer.rs, tests/test.rs
Closes #92 
One of the few questions I had left after doing this was what to do with the `isize_invalid_deserialize` test. The test used variants from the `serde::de::value::Error` enum. This type is now a struct and doesn't have variants anymore so the test wouldn't work without string parsing, which seemed fragile.
=> Update to serde 0.9.X

src/serde/writer.rs
I didn't like the old error message
=> change error message

src/serde/mod.rs
=> Remove sized bounds where appropriate

src/serde/reader.rs, src/serde/writer.rs, tests/test.rs
=> Remove length encoding

src/serde/mod.rs, src/serde/reader.rs, src/serde/writer.rs, tests/test.rs
=> Combine error types

src/serde/reader.rs
It seems we can just read all at once rather than reading byte by byte.
=> Smarter deserialize_bytes and deserialize_byte_buf

src/lib.rs
While introducing selectable endianness in
https://github.com/TyOverby/bincode/pull/103 , the new type parameter
has been hidden from the public `serialize()`, `deserialize()` etc.
functions, and only made available through an alternate API entry point.
The same kind of encapsulation also needs to be performed for the public
`Serializer` and `Deserializer` types.
=> Fix unintentional breaking API change in `Serializer`/`Deserializer`

examples/basic.rs, readme.md
This PR makes the old example work with serde. It also replaces the asserts 
with some output of the encoded/decoded structs, because asserts are boring and an example needs some action.
=> Make example work with serde

src/serde/reader.rs
This PR does the following things in `deserialize_char`:
1. Removes a call to `unwrap()` that was probably impossible to panic 
since `str::from_utf8` checks the encoding, but anyway.
2. Uses a single buffer to read the char into.
3. Replaces the while loop with `read_exact` because the while loop may not
return on malformed input:
```rust
let err = deserialize::<char>(&[0b_1110_0000]).is_err();
println!("{:?}", err);
```
Things I didn't change: 
1. The error gets always created if the compiler isn't smart enough
to move it into the right places. It is boxed, so this means one heap allocation/deallocation
on every call to `deserialize_char`? 
2. The big `UTF8_CHAR_WIDTH` table and the `utf8_char_width` function could be replaced with something like
```rust
match (!buf[0]).leading_zeros() …
```
=> Revamp deserialize_char

src/serde/reader.rs
This PR makes bincode survive garbage input when decoding types that invoke
the `read_vec` function. Currently `read_vec` allocates a vector of the given
length without any sanity checks, which makes it easy to crash the decoder
with extreme values.
Since the `Read` trait does not provide a way to check the size of the 
remaining data, this PR splits `read_vec` into two functions:
1. `read_vec_small` that read vectors the way bincode currently does,
2. `read_vec_large` that tries to read largish vectors in chunks.
On encountering a large vector size, `read_vec` will call `read_vec_large`
to load the vector in reasonable sized chunks. `read_vec_large` avoids allocating
the vector at once and grows it instead. If length turns out to be garbage, 
bincode will reach the end of the data before …
=> Make read_vec more robust

src/serde/reader.rs
@slyrz This should fix the overflow panic that you were talking about earlier
=> call read_bytes iteratively inside of read_vec

examples/basic.rs, src/lib.rs, src/serde/mod.rs, src/serde/reader.rs, src/serde/writer.rs, tests/test.rs
=> make SizeLimit a trait

Cargo.toml, src/lib.rs, src/serde/mod.rs, src/serde/reader.rs, src/serde/writer.rs, tests/test.rs
=> Update to serde 1.0 branch

Cargo.toml, src/de/mod.rs, src/de/read.rs, src/internal.rs, src/lib.rs, src/ser/mod.rs, tests/test.rs
=> WIP Implement nocopy support for bincode

src/de/mod.rs, src/de/read.rs
This PR does two things: 
* Changes `read_vec` to use the special BincodeRead buffer to speed up reading out of a `&[u8]`.
* Fixes a bug in `IoReadReader::forward_read_bytes` and `IoReadReader::forward_read_str` where the internal buffer length wasn't changed via `set_len`.
=> Fix buffer bug

readme.md
The `assert_eq!` macro expects its arguments to satisfy the `Debug` trait as if and when it panics, it'll print out the `Debug` representation.
=> Add Debug derivation to structs of the example in README.md

readme.md
Also, make Vec parameter visible when rendered
=> readme: avoid awkward language

src/de/read.rs, src/internal.rs, src/lib.rs
Closes #163 
I also took the opportunity to rename `IoReadReader` to the less redundant `IoReader`.
=> Internal type names

src/de/mod.rs
Spotted the mistake while skimming over the code.
=> Correct error message

src/de/read.rs
If we don't do this we end up using the generic read_exact method
which is not necessarily optimal. This is especially when
using a specialized Read implementation to go fast.
See https://github.com/TyOverby/bincode/issues/206
=> Forward read_exact() as well as read().

Cargo.toml
MIT license requires that it is shipped with sources. So crates.io archive should have it as well.
=> do not exclude LICENSE.md

Cargo.toml
this is faster, and produces more accurate (bit-exact) round-tripping.
=> bump byteorder version to get transmuting binary float parses

src/de/read.rs
The byte buffer stuff is designed to allow zero copies ... but bincode forces one anyways, to save reallocating its internal `Vec`.
=> Elide unnecessary copy when consuming a byte buffer.

examples/basic.rs, src/config.rs, src/de/mod.rs, src/de/read.rs, src/error.rs, src/internal.rs, src/lib.rs, src/ser/mod.rs, tests/test.rs
closes #160 
closes #156 
closes #164
Basic gist of it is that you can write the following 
```rust
use bincode::{serialize, config};
serialize(&vec![1,2,3]);
// or 
config().big_endian().limit(12).serialize(&vec![1,2,3]);
```
depending on if you want to configure bincode.
Adding new configuration options should be backwards compatible.  All of this should be 0 cost (assuming that the inliner does its work correctly)
=> 2nd implementation of the Config Trait

readme.md
As shown in `examples/basic.rs`, `bincode::Infinite` isn't used anymore.
=> Update README example to match #214 changes

.travis.yml, Cargo.toml, src/de/mod.rs, src/lib.rs, src/ser/mod.rs, tests/test.rs
Closes #236 
This PR adds support for encoding/decoding `i128` and `u128` which were stabilized in `rustc` `1.26.0`, and supported as of `serde` `1.0.60`.
There's a new a disabled-by-default `i128` feature flag in `bincode`, which enables support for 128bit numbers. If `bincode` is compiled on a version of Rust that supports 128bit numbers but doesn't have the `i128` feature enabled then we'll return a custom error at runtime suggesting they enable the feature.
If there's anything you'd like changed let me know. Thanks!
=> Add support for 128bit numbers

src/lib.rs
Without this we end up generating code for all configs unless LTO is on.
=> Make config() inline(always)

Cargo.toml, build.rs, src/de/mod.rs, src/lib.rs, src/ser/mod.rs, tests/test.rs
Fix #250.
Uses autocfg. If you prefer, I can avoid this as @BurntSushi [did in byteorder](https://github.com/dhardy/byteorder/blob/master/build.rs), but this seems like an apt tool for the job so worth making more popular.
Tested on Rustc 1.22.1, 1.31.1 and a recent nightly.
=> Make i128 support automatic for supporting Rustc versions

Cargo.toml
`autocfg` 0.1.1 does not have `rerun_path`, which causes it to compile errors.
=> Fix autocfg version

src/config.rs, src/de/read.rs, src/internal.rs, tests/test.rs
This PR builds on https://github.com/servo/bincode/pull/246 to add `Config::deserialize_from_seed` and `Config::deserialize_from_custom_seed`. The current `Config::deserialize_seed` accepts `& [u8]`; these new methods add support for `R: Read` and `R: BincodeRead<'a>` as well.
There are two changes in addition:
* `deserialize_from_seed` required the `IoReader` struct's impl of `BincodeRead<'static>` to be broadened to `for<'a> BincodeRead<'a>`;
* The 7 `deserialize*` methods ended up with quite a bit of duplication so I tried to minimise this by implementing them in terms of each other.
=> Add more ..._seed variants of deserialize methods

src/de/read.rs
Fixes #260 
This implements a fix for a safety issue found in `fill_buffer` as reported in #260. This is the implementation suggested by @Dr-Emann.
=> improve safety of fill_buffer

Cargo.toml, build.rs, src/de/mod.rs, src/lib.rs, src/ser/mod.rs, tests/test.rs
Bincode only partially relies on whether `serde` decides to enable `i128`. And so, building `bincode` for  Emscripten targets is totally broken on `rustc` >= 1.26.0.
Remove `autocfg` and simply rely on `serde` to determine whether i128 is supported
`autocfg` checks for `i128` support by attempting to compile code to llvm-ir and checking for success or failure. When targeting Emscripten, `i128` can still be compiled to llvm-ir and so `autocfg` believes `i128` support should be enabled. Unfortunately, the Emscripten runtime does not support `i128` despite the LLVM backend supporting it and so it needs to be explicitly disabled. This is the route that `serde` takes here: https://github.com/serde-rs/serde/blob/master/serde/build.rs#L56
Since serde does not add the `deserialize_u128` method to …
=> Fix emscripten build failures due to lack of i128 support

src/lib.rs
This allows the user to retreive concrete types from the
serializer & deserializer output.
This closes https://github.com/servo/bincode/issues/287.
=> Add contraints to {Serializer,Deserializer}Acceptor

src/de/mod.rs, src/error.rs, src/ser/mod.rs
I was getting a bunch of warnings like this:
```
warning: use of deprecated item 'try': use the `?` operator instead
--> bincode/src/ser/mod.rs:416:9
|
416 |         try!(self.add_value(variant_index));
|         ^^^
```
With the latest compiler `cargo 1.40.0 (bc8e4c8be 2019-11-22)`
This change tries to fix them.
=> Fix compile warnings caused by deprecated macros.

.travis.yml, Cargo.toml
Includes changes to travis to re-run the test suite inside a copy
of the prepared package.
Closes: https://github.com/servo/bincode/issues/290
=> Restore shipping tests re bug #290

.mailmap
This PR adds a .mailmap file (see documentation [here](https://github.com/git/git/blob/master/Documentation/mailmap.txt)) to properly merge contributors in `git --shortlog`
=> add mailmap entries

src/de/read.rs
Closes #206 
The default read implementation on slices was not generating efficient code. This custom implementation generates much smaller assembly with fewer function calls.
=> Overoptimize slice reader

src/de/read.rs
Fully fixes #260 
I ran benchmarks with https://github.com/erickt/rust-serialization-benchmarks and couldn't find any appreciable difference in the time it took to execute. If anything, the new method runs faster.
=> remove unsafe code in IoReader

src/config.rs, src/de/mod.rs, src/de/read.rs, src/internal.rs, src/lib.rs, src/ser/mod.rs, tests/test.rs
This is a **_very_** early PR that explores if its possible to expose the `Serializer` and `Deserializer` in a way that would allow us to expand options in the future.
- expose the `DefaultOptions` and `OptionsExt` traits publicly.
- expose `Serializer` and `Deserializer` publicly.
- keep all other traits and structs `Compound, Options` private
I believe this would allow us to implement any future improvements in a backwards compatible manner. `OptionsExt` can't be implemented by 3rd party crates since it is sealed, so adding new methods should be fine.
- A custom ByteOrder trait was created that provides a thin wrapper over the `byteorder` trait.
This enables us to add features to our endian behavior in the future without breaking the public API. e.g. making varint respect the endian …
=> expose default options and serializers

Cargo.toml, src/config.rs, src/de/mod.rs, src/ser/mod.rs, tests/test.rs
Resolves #319 
This is a continuation of PR #271 based on feedback in that PR. The primary change is to use a config option instead of a feature in order to use varint sequence lengths and discriminants.
=> Varint enum tags and lengths

src/config/legacy.rs, src/config/mod.rs, src/config/trailing.rs, src/de/mod.rs, src/de/read.rs, src/error.rs, src/internal.rs, src/lib.rs, tests/test.rs
Closes #193 
There were two design possibilities I considered for tackling this problem. The current one changes the impls on `SliceReader` to be impls for `&mut SliceReader`. This allows me to access it after passing it to the deserializer. The other option would be to allow `pub(restricted)` access to the reader field of the deserializer and access it from there.
=> Reject trailing bytes

src/de/mod.rs
Having these in the `impl` block with a generic `R` paramter would make them unusable, at least without type annotations:
error[E0282]: type annotations needed
--> msg_socket2/src/socket.rs:45:32
|
45 |         let mut deserializer = Deserializer::with_reader(bytes.as_slice(), DefaultOptions::new());
|                                ^^^^^^^^^^^^^^^^^^^^^^^^^ cannot infer type for type parameter `R`
error: aborting due to previous error
For more information about this error, try `rustc --explain E0282`.
Moving these into separate `impl` blocks, which set the type of the `Deserializer` to the return type of the functions, fixes this error.
=> Fix Deserializer::{from_slice, with_reader} types

src/config/mod.rs
They should be Copy/Clone as the rest of the Options
Closes #341
=> Fix `WithOtherTrailing` and `WithOtherIntEncoding`

src/config/mod.rs, src/lib.rs
Due to historical reasons, the default options used by bincode for the helper functions at the root of the crate differ from the options in the `config` module.
Changing the default options is a breaking change, so until a decision is made, we can at least document the current behavior.
Related issue: #348
=> Update docs to highlight differences between DefaultOptions and fns

readme.md
Puts some prominent text into the `readme.md` regarding some use cases
that are likely to be common, along with a few hopefully helpful
pointers to avoid footguns.
Closes #345, closes #216, addresses #240, #266.
=> Address questions regarding suitability for storage and untrusted inputs

Cargo.toml, benches/varint.rs, src/config/int.rs, src/de/mod.rs, src/de/read.rs
@ZoeyR After this meets with your approval I'd like the chance to verify that it fixes the performance issue we're seeing before you merge.
=> Optimize varint parsing
