bincode-org/bincode

src/reader.rs

Currently you get a panic on invalid input.

Perform sanity check when reading enum variant.

---

Cargo.toml
src/lib.rs
src/reader.rs
src/test.rs
src/writer.rs

Read strings in one go, not byte-by-byte.

---

src/reader.rs
src/test.rs
src/writer.rs

Update to using Debug over Show.
Update the Error impls.

Update to latest nightly.

---

src/refbox.rs

These make them more flexible.

Add some more trait impls and methods to StrBox and SliceBox

---

Cargo.toml

CC https://github.com/servo/servo/pull/8446

Update byteorder crate

---

src/refbox.rs

Impl Deserialize for non-'static lifetimes

---

src/serde/reader.rs
src/serde/writer.rs
tests/test.rs

I don't think roundtripping ever worked for chars

fix char serialization and deserialization

---

src/serde/writer.rs

Don't panic.

---

src/serde/mod.rs
src/serde/reader.rs
tests/test.rs

Closes #110 
Open questions:  
Do we want to use a struct-like variant or a tuple-like variant? Right now I implemented it as a struct-like.

Remove InvalidEncoding struct

---

src/lib.rs
src/serde/mod.rs

Always find the preallocated size

Eager prealloc no inline

---

src/serde/reader.rs

remove read_bytes

---

src/internal.rs

Correctlly report the cause of IoError

---

src/de/read.rs
src/internal.rs
src/lib.rs

Seal SizeLimit and BincodeRead

---

src/de/read.rs
src/internal.rs

Remove naming redundancy with IoError

---

src/internal.rs

take reader and writer by value

---

.gitignore
Cargo.toml
src/lib.rs

rename doc functions

---

src/de/mod.rs
src/internal.rs

uncapitalize error messages

---

src/internal.rs
src/lib.rs

remove references to buffer type

---

Cargo.toml
src/de/mod.rs
src/internal.rs

add ErrorKind::DeserializeAnyNotSupported

---

Cargo.toml
src/de/mod.rs
src/de/read.rs
src/internal.rs
tests/test.rs

177 invalid encodings

---

Cargo.toml

The crate is useful more generally than just for network programming

Add encoding crates.io category

---

src/de/read.rs

I did some cleanup while studying the source of bincode.

Cleanup of de/read.rs

---

Cargo.toml

I had a legal name change so I'm updating the entry here to reflect my current name. I can also just remove the name if you'd prefer that.

update author name to current legal name
